import "../styles/globals.scss";
import { Provider } from "react-redux";
import { Providers } from "lastHomework/redux/provider";
import { store } from "lastHomework/redux/store/store";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
